version: "2"
services:
    web:
        build: .
        ports:
            - 80:80
        links:
            - redis
        volumes:
            - ./:/var/www/
            - ./html/.user.ini:/usr/local/etc/php/php.ini
        environment:
            REDISCLOUD_URL: tcp://redis:6379
            SHOPIFY_API_KEY: deadd5cf0ff236a44901b70e60fbceb2
            SHOPIFY_PASSWORD: 16b875a75aaeedb782ad4dccfe8e847d
            MYSHOPIFY_DOMAIN: school-bus-drivers-unite.myshopify.com
    redis:
        image: redis
        volumes:
            - ./data/redis:/data
        ports:
            - 6379:6379
